/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseForm: typeof import('./components/BaseForm.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    IconArrow: typeof import('./assets/svg/IconArrow.vue')['default']
    IconEye: typeof import('./assets/svg/IconEye.vue')['default']
    LayoutAccent: typeof import('./layouts/LayoutAccent.vue')['default']
    LayoutSplit: typeof import('./layouts/LayoutSplit.vue')['default']
    Page404: typeof import('./pages/Page404.vue')['default']
    PageComplete: typeof import('./pages/PageComplete.vue')['default']
    PageForm: typeof import('./pages/PageForm.vue')['default']
    PageMenu: typeof import('./pages/PageMenu.vue')['default']
    PageNotify: typeof import('./pages/PageNotify.vue')['default']
    PageWelcome: typeof import('./pages/PageWelcome.vue')['default']
    PageWelcomeback: typeof import('./pages/PageWelcomeback.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreensMenu: typeof import('./pages/ScreensMenu.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}
